### ISSUE TITLE
Perform basic frontend maintenance

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/student_explorer#260]
In looking at the application during other reviews for 2.8.0, I both remembered and noticed some issues related to `jquery` and other frontend dependencies.

1) When looking at pages with tables, there is a console error like this:

```
jquery.js:4055 Uncaught TypeError: dataAttributes.hasOwnProperty is not a function
    at Tooltip.getOptions (bootstrap.js:1508:26)
    at Tooltip.init (bootstrap.js:1471:27)
    at new Tooltip (bootstrap.js:1441:10)
    at HTMLSpanElement.<anonymous> (bootstrap.js:1943:51)
    at Function.each (jquery.js:381:19)
    at jQuery.fn.init.each (jquery.js:203:17)
    at jQuery.fn.init.Plugin [as tooltip] (bootstrap.js:1937:17)
    at HTMLDocument.<anonymous> (index.js:11:34)
    at mightThrow (jquery.js:3762:29)
    at process (jquery.js:3830:12)
```

2) In mobile viewports, the hamburger icon does not work and in fact throws a console error:

```
Uncaught TypeError: can't convert Object to string
    Plugin https://test-studentexplorer.tl.it.umich.edu/static/bootstrap/dist/js/bootstrap.894d79839fac.js:723
    jQuery 2
    Plugin https://test-studentexplorer.tl.it.umich.edu/static/bootstrap/dist/js/bootstrap.894d79839fac.js:718
    <anonymous> https://test-studentexplorer.tl.it.umich.edu/static/bootstrap/dist/js/bootstrap.894d79839fac.js:756
    jQuery 2
```

Both of these seem to be resolved by picking up minor or patch fixes to a couple libraries.

In addition, if it's non-disruptive, we should bump the Node version to 16 (from 12, since 12 is out of maintenance mode this year: https://nodejs.org/en/about/releases/).

**Comment by ssciolla** [comment]
Node version is still 12; there is an issue in `Dockerfile`.
