### ISSUE TITLE
Fix 0 user count on SE usage page

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/student_explorer#40]
On SE dev and localhost it has a 0 count on the /usage page.

It would be nice to figure out why this is

@zqian commented about this possible related stacktrace

```
student_explorer | INFO student_explorer.common.db_util Student Explorer Daily Tables
student_explorer | DEBUG django.template Exception while resolving variable 'advisor' in template 'usage.html'.
student_explorer | Traceback (most recent call last):
student_explorer |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
student_explorer |     (bit, current))  # missing attribute
student_explorer | VariableDoesNotExist: Failed lookup for key [advisor] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x7fb38f4f4398>>, 'last_updated': datetime.datetime(2018, 11, 25, 0, 0, tzinfo=<UTC>), 'user': <SimpleLazyObject: <User: admin>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7fb38c499d90>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fb38c436810>, u'request': <WSGIRequest: GET '/usage/'>}, {}, {'studentsCount': 0, 'dailyData': [{'color': '#ff7f0e', 'values': [], 'key': 'Unique Students Viewed'}, {'color': '#7777ff', 'values': [{'date': 1544140800, 'count': 1}], 'key': 'Unique Users Count', 'area': 'true'}], u'view': <usage.views.UsageView object at 0x7fb38c436990>, 'usersCount': 0}]"
student_explorer | DEBUG django.template Exception while resolving variable 'query_user' in template 'usage.html'.
student_explorer | Traceback (most recent call last):
student_explorer |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
student_explorer |     (bit, current))  # missing attribute
student_explorer | VariableDoesNotExist: Failed lookup for key [query_user] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x7fb38f4f4398>>, 'last_updated': datetime.datetime(2018, 11, 25, 0, 0, tzinfo=<UTC>), 'user': <SimpleLazyObject: <User: admin>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7fb38c499d90>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fb38c436810>, u'request': <WSGIRequest: GET '/usage/'>}, {}, {'studentsCount': 0, 'usersCount': 0, 'dailyData': [{'color': '#ff7f0e', 'values': [], 'key': 'Unique Students Viewed'}, {'color': '#7777ff', 'values': [{'date': 1544140800, 'count': 1}], 'key': 'Unique Users Count', 'area': 'true'}], u'advisorsurl': u'/advisors/', u'mystudentsurl': u'', u'view': <usage.views.UsageView object at 0x7fb38c436990>}]"
```

**Comment by mfldavidson** [comment]
Not sure if this info is helpful at all I was curious about this so took a look.

I am seeing "Download Users for the Academic Year 2018-2019" as 9 and it returns admin, Matthew, Zhen, Daniel D, Dan B, me, Sara R, Phil G, and (weirdly enough) Chris Teplovs. I don't have permissions to the admin page in the dev site so I can't see if Chris Teplovs actually has accessed it this year but I find that hard to believe.

21 unique students are showing as viewed for the academic year, which for the dev site would make sense.
